### ISSUE TITLE
Application DSP2

### ISSUE THREAD

**Issue by AlKoulounil** [thelia-modules/CmCIC#17]
Bonjour, je suis Lucas Baire. Je fait partie du groupe de bénévoles qui gère l'informatique de notre association, Acrimed. Nous utilisons Thelia depuis plusieurs années et comme nous sommes au Crédit Mutuel, nous réalisons nos paiements par CB avec Monetico et en utilisant ce module.

Jusqu'ici tout fonctionne bien.

Il y a la DSP2 qui arrive prochainement et ce module va avoir besoin d'être updaté. Je suis en train de regarder de mon côté pour m'en occuper. Si quelqu'un a déjà commencé à bosser là-dessus, qu'il me prévienne. Et sinon, si vous voulez, je peux me charger de faire les modifs et les commiter ici. Je ne pense pas avoir les droits pour faire le merge vers la branche principale en revanche.

Au passage, je suis dévellopeur en Freelance donc si quelqu'un utilise ce module et a besoin d'aide pour le passage à la DSP2, je serais ravi d'offrir mes services. N'hésitez pas à me contacter.

Bonne journée,

Lucas Baire

**Comment by roadster31** [comment]
Bonjour, et merci pour ce message.

Tu peux tout à fait contrubuer à ce module. Le plus simple est de le forker, de faire tes modifications, et de soumettre une pull-request.

Nous intégrerons tes modifications avec plaisir.

**Comment by pierr0t** [comment]
Bonjour,
Je vois que Lucas a une nouvelle version "dsp2" de ce plugin, je me demandais, n'étant pas un grand spécialiste de GitHub, si elle était utilisable, si je devais attendre qu'elle soit "mergée" dans la branche officielle, si .. 
En tous cas grand merci à Lucas pour ce travail, je suis en train de mettre à jour une 10aine de sites Thelia avec divers systèmes de paiement, 3 sites Spip avec là aussi divers systèmes, plus un dev interne avec Stripe, c'est pas du gateau :-(

**Comment by roadster31** [comment]
Résolu par #18
