### ISSUE TITLE
Society code (com_soc) doest not support dashes

### ISSUE THREAD

**Issue by GhaziBahri** [thelia-modules/CmCIC#19]
I tried to add my Society code (com_soc) that contains a dash  but it seems that the regex patern  declared in preg_match ( ) function in Controller CmcicSaveConfig.php does not match with such Society code.

An esay fix would be to add `\-` to the patern :

https://github.com/GhaziBahri/CmCIC/pull/1/commits/6e03f55b6edf86a02805d515dc9fd0a21b50ad61#diff-3f8b2df039483a55cfd85890422a1153R88

**Comment by roadster31** [comment]
Could you please submit a PR ?

**Comment by GhaziBahri** [comment]
Done :)

**Comment by roadster31** [comment]
Soldev by #20
